apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pt-rolebinding
  namespace: pt
subjects:
- kind: ServiceAccount
  name: pt-sa
  namespace: pt
roleRef:
  kind: Role
  name: pt-role
  apiGroup: rbac.authorization.k8s.io

